### ISSUE TITLE
cant we capture open event  of a file

### ISSUE THREAD

**Issue by ramandraju** [thekid/inotify-win#24]
Hi, like inotify tools in linux cant we capture open event of a file  from listening folder using this. if not ,is there any alternative to achieve this

**Comment by thekid** [comment]
INotify-Win is based on the [FileSystemWatcher](https://msdn.microsoft.com/de-de/library/system.io.filesystemwatcher(v=vs.110).aspx) class. It raises the following events:

| Event | Description |
| ----- | ----------- |
| Changed | Occurs when a file or directory in the specified Path is changed. |
| Created | Occurs when a file or directory in the specified Path is created. |
| Deleted | Occurs when a file or directory in the specified Path is deleted. |
| Disposed | Occurs when the component is disposed by a call to the Dispose method. |
| Error | Occurs when the instance of FileSystemWatcher is unable to continue monitoring changes or when the internal buffer overflows. |
| Renamed | Occurs when a file or directory in the specified Path is renamed. |

Since there is no "Opened" event, we cannot implement this.
