### ISSUE TITLE
Do you have a working Windows batch example?

### ISSUE THREAD

**Issue by pandel** [thekid/inotify-win#33]
Hi!

Just recently found your port and would love to try it under Windows! But I seem to be unable to get something working like

"inotifywait -m -e -create d:/examplefolder | windows_batch_to_do_something.cmd"

It is not about inotify not working correctly but more about how to use it in a concrete situation. I am unable to use Cygwin on the Windows machine, so I am stuck with win cmd...

Perhaps you already used it in such a way and have a small example :-) - if not, nevertheless, keep up the good work!

Regards
Holger

**Comment by thekid** [comment]
Not with `cmd.exe`, because its `for` loop is buffered, that is, it will only start processing once the command in it has finished executing, but with Powershell:

```powershell
.\inotifywait.exe -m --format="%f" Videos | ForEach { echo "Sync $_" }
```

Here's what that would do:

![image](https://user-images.githubusercontent.com/696742/102638991-a8cf0880-4158-11eb-811d-c83899318fe1.png)

Instead of `echo`, you'd use a more elaborate concept of course :-)

**Comment by pandel** [comment]
As an old Linux kid I really don't like Powershell and am totally unfamiliar with it (as I hate its syntax!) - but you're right, that's the way to go!

Many many thanks!
